### ISSUE TITLE
Error : content-length with this repo zip archive.

### ISSUE THREAD

**Issue by Askhento** [saulpw/unzip-http#19]
What is happening here ?

```
>>> import unzip_http
>>> rzf = unzip_http.RemoteZipFile("https://github.com/saulpw/unzip-http/archive/refs/heads/master.zip")
>>> rzf.namelist()
github.com Accept-Ranges header ('') is not 'bytes'--trying anyway
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/askhento/.local/lib/python3.10/site-packages/unzip_http.py", line 150, in namelist
    return list(r.filename for r in self.infoiter())
  File "/home/askhento/.local/lib/python3.10/site-packages/unzip_http.py", line 150, in <genexpr>
    return list(r.filename for r in self.infoiter())
  File "/home/askhento/.local/lib/python3.10/site-packages/unzip_http.py", line 159, in infoiter
    self.zip_size = int(resp.headers['Content-Length'])
  File "/home/askhento/.local/lib/python3.10/site-packages/urllib3/_collections.py", line 260, in __getitem__
    val = self._container[key.lower()]
KeyError: 'content-length'
```
Using WSL2 on windows 10.

**Comment by saulpw** [comment]
Hi @Askhento, github.com is not returning the Content-Length header, which is required.  According to https://stackoverflow.com/questions/76162297/github-api-not-always-returning-content-length-header, it might be possible to affect the returned headers by sending certain headers.   If you do a HEAD request manually with e.g. curl, you can experiment with sending different headers, and seeing which headers are returned.  If you find something that works reliably, we can try adding to the library.  Good luck.
